export const bannersDefaults = {
  bannerType: 'hd_banner',
  size: '2x4',
  material: 'vinyl_13oz',
  sides: 'single_sided',
  finishing: 'hemmed_grommets',
  quantity: 10,
  turnaround: 'standard_48h',
  hem: 'all_sides',
  grommets: 'every_2ft',
  polePocket: 'none',
  windSlits: 'no',
  webbing: 'no',
  notes: '',
};
